services:
  db:
    image: postgres:16.4
    container_name: inventory_control_db
    env_file:
      - .env-none-dev
    ports: 
      - 5432:5432

  inventory_control:
    image: inventory_control_image
    build:
      context: .
    container_name: inventory_control_app
    env_file:
      - .env-none-dev
    depends_on:
      - db
    command: ["/app/docker/app.sh"]
    ports:
      - 7777:8000