services:
  inventory_control:
    image: inventory_control_image
    build:
      context: .
    container_name: inventory_control_app
    env_file:
      - .env
    depends_on:
      - db
    command: ["/app/scripts/app.sh"]
    ports:
      - 8000:8000

  db:
    image: postgres:16.4
    container_name: inventory_control_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: