services:
  # db:
  #   image: postgres:16.4
  #   container_name: inventory_control_db
  #   env_file:
  #     - .env
  #   ports: 
  #     - 5432:5432
  inventory_control:
    image: inventory_control_image
    build:
      context: .
    container_name: inventory_control_app
    env_file:
      - .env
    depends_on:
      - test_db
    command: ["/app/scripts/app.sh"]
    ports:
      - 7777:8000

  test_db:
    image: postgres:16.4
    container_name: inventory_control_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: